# shallow clone
clone_depth: 10

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

os: Visual Studio 2017

environment:
  # Tell msys2 to add mingw64 to the path
  MSYSTEM: MINGW64
  # Tell msys2 to inherit the current directory when starting the shell
  CHERE_INVOKING: 1
  matrix:
    - BUILD_TYPE: msvc

branches:
  only:
    - master

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir %BUILD_TYPE%_build
  - cd %BUILD_TYPE%_build
  - ps: |
          # redirect stderr and change the exit code to prevent powershell from cancelling the build if cmake prints a warning
          cmd /C 'cmake -G "Visual Studio 15 2017 Win64" -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 -DCMAKE_USE_OPENSSL=0 .. 2>&1 && exit 0'
  - cd ..

build_script:
  - ps: |
          # https://www.appveyor.com/docs/build-phase
          msbuild msvc_build/citra.sln /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: |
          $GITDATE = $(git show -s --date=short --format='%ad') -replace "-",""
          $GITREV = $(git show -s --format='%h')

          $RELEASE_DIST = "head"

          # Where are these spaces coming from? Regardless, let's remove them
          $MSVC_BUILD_ZIP = "citra-windows-msvc-$GITDATE-$GITREV.zip" -replace " ", ""

          # set the build names as env vars so the artifacts can upload them
          $env:BUILD_ZIP = $MSVC_BUILD_ZIP

          rm .\msvc_build\bin\release\*.pdb

          mkdir $RELEASE_DIST
          Copy-Item .\msvc_build\bin\release\* -Destination $RELEASE_DIST -Recurse
          Remove-Item "$RELEASE_DIST\tests.exe"
          Remove-Item "$RELEASE_DIST\citra.exe"
          Copy-Item -path .\license.txt -destination $RELEASE_DIST\2.license.txt
          Copy-Item -path ".\Text Files\1.ReadMe First.txt" -destination $RELEASE_DIST
          7z a -tzip $MSVC_BUILD_ZIP $RELEASE_DIST\*

artifacts:
  - path: $(BUILD_ZIP)
    name: build
    type: zip

deploy:
 - provider: Environment
   name: ghreleases
   on:
     branch: master
